### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Meryalvhe-Traffic-Light#1]
# Revisión - Aprobado :white_check_mark:

## Feedback
- Buen proyecto @Meryalvhe 🐱‍💻

## Estilo de código y limpieza
- Bien resuelto

## Mejores prácticas/comentarios
- Muy bien resuelta la lógica de tu proyecto
- Recuerda que los nombres de los componentes así como su archivo `.jsx` deben ir en mayúsculas 
![Captura de pantalla de 2024-04-23 21-21-42](https://github.com/4GeeksAcademy/Meryalvhe-Traffic-Light/assets/139759297/15108ec0-b156-4283-a1d4-300fd857bbc2)
- En el componente Home estás importando una imagen que luego no estás utilizando (puedes eliminarla sin problemas) 
![Captura de pantalla de 2024-04-23 21-22-43](https://github.com/4GeeksAcademy/Meryalvhe-Traffic-Light/assets/139759297/65542029-b860-41d6-9937-b7761ffa6952)
- En tu componente TrafficLight recuerda cambiar ese class por className 
![Captura de pantalla de 2024-04-23 21-26-12](https://github.com/4GeeksAcademy/Meryalvhe-Traffic-Light/assets/139759297/48fe8bb6-07e1-4bbd-9582-78d851a79a32)
- La importación de estilos en el componente TrafficLight que has hecho así 
![Captura de pantalla de 2024-04-23 21-27-50](https://github.com/4GeeksAcademy/Meryalvhe-Traffic-Light/assets/139759297/f1befed4-fbd0-45f1-976f-3161d502b7e0) 
Debería ser así 
![Captura de pantalla de 2024-04-23 21-28-01](https://github.com/4GeeksAcademy/Meryalvhe-Traffic-Light/assets/139759297/6d5e5d46-d6e2-4117-850d-9a204bc95af1)

**Comment by Meryalvhe** [comment]
Gracias Edo, 
Tomo nota para no cometer los mismos errores :)
